services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php_app
        volumes:
            - .:/var/www/html
            - ~/.config/stripe:/root/.config/stripe
        ports:
            - "8080:80"
        environment:
            WWWUSER: '${WWWUSER:-sl}'
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
